from __future__ import annotations

from math import isfinite
from typing import Literal

from pydantic import Field, field_validator, model_validator

from harborrag_core.base import StrictModel
from harborrag_core.schemas.ids import DocumentId, DocumentVersionId
from harborrag_core.schemas.vector import SparseVector


class SparseEncoderProfile(StrictModel):
    """Version every choice needed to reproduce BM25-compatible vectors."""

    profile_id: str = Field(min_length=1)
    implementation: Literal["bm25-hashed-v1"] = "bm25-hashed-v1"
    k: float = Field(default=1.2, gt=0)
    b: float = Field(default=0.75, ge=0, le=1)
    fixed_avg_len: float = Field(default=256.0, gt=0)
    hash_space: int = Field(default=2_147_483_647, ge=1024)
    tokenizer: Literal["unicode-word-v1"] = "unicode-word-v1"
    lowercase: bool = True
    stopwords: tuple[str, ...] = ()
    stopword_profile: str = Field(default="none", min_length=1)
    stemmer_profile: Literal["none"] = "none"
    language_policy: str = Field(default="multilingual", min_length=1)
    identifier_policy: str = Field(default="source-identifiers-v1", min_length=1)
    qdrant_idf_modifier: Literal["idf"] = "idf"

    @model_validator(mode="after")
    def validate_stopwords(self) -> SparseEncoderProfile:
        normalized = tuple(word.casefold() if self.lowercase else word for word in self.stopwords)
        if any(not word.strip() for word in normalized):
            raise ValueError("sparse stopwords must be non-empty")
        if len(set(normalized)) != len(normalized):
            raise ValueError("sparse stopwords must be unique")
        return self


class SparseEncoding(StrictModel):
    profile_id: str = Field(min_length=1)
    vector: SparseVector
    token_count: int = Field(ge=0)


class ChunkRepresentation(StrictModel):
    """Dense and sparse retrieval representations for one canonical chunk."""

    chunk_id: str = Field(min_length=1)
    dense_vector: list[float]
    sparse_vector: SparseVector

    @field_validator("dense_vector")
    @classmethod
    def validate_dense_vector(cls, values: list[float]) -> list[float]:
        if not values or not all(isfinite(value) for value in values):
            raise ValueError("dense representation values must be non-empty and finite")
        return values


class RepresentationSet(StrictModel):
    """Version-addressed representations generated by one profile pair."""

    document_id: DocumentId
    document_version_id: DocumentVersionId
    dense_profile_id: str = Field(min_length=1)
    sparse_profile_id: str = Field(min_length=1)
    dense_dimension: int = Field(ge=1)
    records: tuple[ChunkRepresentation, ...]

    @model_validator(mode="after")
    def validate_records(self) -> RepresentationSet:
        chunk_ids = tuple(record.chunk_id for record in self.records)
        if len(set(chunk_ids)) != len(chunk_ids):
            raise ValueError("representation chunk IDs must be unique")
        if any(len(record.dense_vector) != self.dense_dimension for record in self.records):
            raise ValueError("dense representation dimensions must match the profile")
        return self
