"""Compatibility exports for the shared runtime graph catalog."""

from harborrag_runtime.tools.graph_catalog import (
    CHUNK_PROPERTIES,
    COMMON_NODE_PROPERTIES,
    DOCUMENT_OWNED_PROPERTIES,
    ENTITY_PROPERTIES,
    GRAPH_NODE_KINDS,
    GRAPH_RELATION_TYPES,
    ONTOLOGY_SCHEMA_VERSION,
    RELATES_PROPERTIES,
    SEMANTIC_SCHEMA_VERSION,
    STRUCTURAL_SCHEMA_VERSION,
    describe_graph_payload,
)

__all__ = [
    "CHUNK_PROPERTIES",
    "COMMON_NODE_PROPERTIES",
    "DOCUMENT_OWNED_PROPERTIES",
    "ENTITY_PROPERTIES",
    "GRAPH_NODE_KINDS",
    "GRAPH_RELATION_TYPES",
    "ONTOLOGY_SCHEMA_VERSION",
    "RELATES_PROPERTIES",
    "SEMANTIC_SCHEMA_VERSION",
    "STRUCTURAL_SCHEMA_VERSION",
    "describe_graph_payload",
]
