"""Scope-aware short-term, working, and long-term memory for HarborRAG."""

from __future__ import annotations

from harborrag_core.ports.conversation import (
    ConversationIdentity,
    ConversationMemory,
    ConversationRepository,
    ConversationSessions,
    ConversationTurn,
    new_session_id,
)

from .config import MemoryManagerConfig
from .context import (
    NO_AFFINITY,
    CondenseResult,
    ExtractedFact,
    MemoryContext,
    MemoryContextBuilder,
    MemoryExtractor,
    MemoryPolicy,
    MemoryRecall,
    ScoringContext,
    TypeAffinity,
    approximate_tokens,
    recalled_entity_ids,
    type_weight,
)
from .errors import MemoryConfigurationError, MemoryError, MemoryScopeError
from .manager import MemoryManager, MemorySnapshot
from .schemas import (
    Memory,
    MemoryEmbedder,
    MemoryEntityResolver,
    MemoryIndex,
    MemoryMatch,
    MemoryOwner,
    MemoryQuery,
    MemoryRepository,
    MemoryScope,
    MemoryType,
    ResolvedEntity,
    new_memory_id,
    scope_owner_fields,
    visible_to,
)
from .tiers import (
    InMemoryWorkingMemoryStore,
    LongTermMemory,
    ShortTermMemory,
    WorkingMemory,
    WorkingMemoryStore,
)

__all__ = [
    "NO_AFFINITY",
    "CondenseResult",
    "ConversationIdentity",
    "ExtractedFact",
    "ConversationMemory",
    "ConversationTurn",
    "InMemoryWorkingMemoryStore",
    "LongTermMemory",
    "ConversationRepository",
    "ConversationSessions",
    "Memory",
    "MemoryConfigurationError",
    "MemoryContext",
    "MemoryContextBuilder",
    "MemoryEmbedder",
    "MemoryEntityResolver",
    "MemoryError",
    "MemoryExtractor",
    "MemoryIndex",
    "MemoryManager",
    "MemoryManagerConfig",
    "MemoryMatch",
    "MemoryOwner",
    "MemoryPolicy",
    "MemoryQuery",
    "MemoryRecall",
    "MemoryRepository",
    "MemoryScope",
    "MemoryScopeError",
    "MemorySnapshot",
    "MemoryType",
    "ResolvedEntity",
    "ScoringContext",
    "ShortTermMemory",
    "TypeAffinity",
    "WorkingMemory",
    "WorkingMemoryStore",
    "approximate_tokens",
    "new_memory_id",
    "new_session_id",
    "recalled_entity_ids",
    "scope_owner_fields",
    "type_weight",
    "visible_to",
]
