"""Provider-independent vector and graph indexing records and queries."""

from harborrag_core.ingestion import (
    GRAPH_SCHEMA_VERSION,
    GraphEdgeRecord,
    GraphEntityType,
    GraphNodeRecord,
    GraphOwnershipScope,
    GraphProjectionManifest,
    GraphProjectionVerification,
    GraphSchemaMigrationVerification,
    ProjectionManifest,
    VectorEvidenceRecord,
    VectorProjectionBatch,
    VectorProjectionManifest,
    VectorProjectionVerification,
)
from harborrag_core.schemas.vector import (
    FilterOperator,
    HybridSearchQuery,
    SparseSearchQuery,
    SparseVector,
    VectorDistance,
    VectorFilter,
    VectorFilterCondition,
    VectorIndexRecord,
    VectorIndexScanPage,
    VectorIndexSpec,
    VectorSearchQuery,
    VectorSearchResult,
    VectorStoreCapabilities,
)

__all__ = [
    "FilterOperator",
    "GRAPH_SCHEMA_VERSION",
    "GraphEdgeRecord",
    "GraphEntityType",
    "GraphNodeRecord",
    "GraphOwnershipScope",
    "GraphProjectionManifest",
    "GraphProjectionVerification",
    "GraphSchemaMigrationVerification",
    "HybridSearchQuery",
    "ProjectionManifest",
    "SparseSearchQuery",
    "SparseVector",
    "VectorDistance",
    "VectorEvidenceRecord",
    "VectorFilter",
    "VectorFilterCondition",
    "VectorIndexRecord",
    "VectorIndexScanPage",
    "VectorIndexSpec",
    "VectorProjectionBatch",
    "VectorProjectionManifest",
    "VectorProjectionVerification",
    "VectorSearchQuery",
    "VectorSearchResult",
    "VectorStoreCapabilities",
]
